site_name: aiida-defects-neb
repo_url: https://github.com/verdi-group/aiida-defects-neb
repo_name: aiida-defects-neb

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - index.md
  - setup.md
  - quickstart.md
  - developer.md